const ARTICLES = [
  {t:'Bem-vindo ao time',k:'inicio parceria cadastro autonomia suporte regras',s:'Entenda o que é a Osasco Express e como funciona sua participação como parceiro autônomo.',b:`<h2>O que é a Osasco Express?</h2><p>A Osasco Express organiza operações de delivery para estabelecimentos clientes. A equipe coordena reservas, suporte durante os períodos, registros operacionais e pagamentos dos parceiros.</p><h2>Como funciona a parceria?</h2><p>Você atua como parceiro autônomo, sem exclusividade, salário fixo, jornada obrigatória ou garantia permanente de reservas. Você informa sua disponibilidade e decide se aceita os períodos oferecidos. Depois da confirmação, a operação passa a contar com seu comparecimento.</p><h2>Antes de começar</h2><p>Confirme endereço, data, horário e cliente. Esteja com motocicleta regular, CNH válida, celular com internet, aplicativo funcionando, bateria suficiente, bag própria adequada e equipamentos de segurança.</p><div class='summary'><strong>Resumo:</strong> disponibilidade não é confirmação; reserva confirmada exige compromisso; dúvidas operacionais devem seguir os canais oficiais.</div>`},
  {t:'Chegou na loja',k:'chegada loja grupo horario diaria presença online',s:'Veja o procedimento obrigatório assim que chegar ao ponto confirmado.',b:`<h2>1. Avise sua chegada</h2><p>Assim que chegar, envie uma mensagem no grupo da operação. Esse aviso registra o horário de comparecimento e permite a conferência da diária garantida.</p><h2>2. Abra o aplicativo</h2><p>Entre no aplicativo utilizado pela operação, confira sua conexão e fique online.</p><h2>3. Confirme com a loja</h2><p>Pergunte se seu nome aparece disponível no sistema. Caso não apareça, não fique aguardando em silêncio: avise a loja e o suporte para corrigir antes do primeiro pedido.</p><h2>Mensagem sugerida</h2><p>“Boa noite, cheguei à loja e já estou online.”</p>`},
  {t:'Agora é só ficar pronto',k:'aguardar pedido disponível celular bateria internet ponto',s:'Como permanecer disponível sem perder chamadas.',b:`<p>Depois de registrar a chegada, permaneça próximo ao ponto e disponível no aplicativo. Mantenha internet ativa, som e notificações ligados, bateria suficiente e bag pronta.</p><h2>Não saia do ponto sem avisar</h2><p>Uma saída sem comunicação pode fazer a operação acreditar que existe cobertura quando, na prática, não há parceiro disponível.</p><h2>Se o aplicativo fechar</h2><p>Abra novamente, confira se continua online e avise o grupo caso tenha ficado indisponível.</p>`},
  {t:'Tocou entrega',k:'aceitar chamada despacho automático coleta pedido',s:'O que fazer quando uma nova entrega aparecer.',b:`<p>Ao receber uma chamada, confira a identificação do pedido e aceite rapidamente. O despacho considera quem está online e disponível.</p><h2>Depois de aceitar</h2><p>Dirija-se à área de retirada, informe o pedido e aguarde a liberação. Não marque como coletado antes de receber e conferir todos os itens.</p><h2>Se não puder realizar</h2><p>Não ignore repetidamente. Informe imediatamente no grupo o motivo e aguarde orientação.</p>`},
  {t:'Confira antes de sair da loja',k:'conferir pedido bebida sobremesa endereço pagamento maquininha taxa',s:'Checklist completo para evitar retorno, prejuízo e reclamações.',b:`<p>Antes de sair, confira número do pedido, nome do cliente, quantidade de volumes, bebidas, sobremesas, adicionais, endereço, observações e forma de pagamento.</p><h2>Maquininha</h2><p>Quando houver pagamento na entrega, confirme com a loja se precisa levar maquininha, qual valor deve ser cobrado e qual forma de pagamento está registrada.</p><h2>Taxa</h2><p>Confira a taxa antes de sair. Se estiver errada ou ausente, peça a correção diretamente à loja durante o período.</p><div class='summary'><strong>Regra prática:</strong> pedido conferido antes de sair evita quase todos os problemas que depois exigem retorno.</div>`},
  {t:'Voltando da entrega',k:'retorno loja finalização app disponível',s:'Finalize corretamente e sinalize seu retorno.',b:`<p>Após concluir a entrega, finalize o pedido no aplicativo conforme o procedimento da plataforma e retorne ao ponto. Ao chegar, permaneça novamente disponível.</p><h2>Não acumule entregas abertas</h2><p>Uma entrega não finalizada pode impedir novas chamadas ou deixar o controle incorreto. Se o aplicativo não permitir finalizar, envie captura de tela no grupo e acione o suporte.</p>`},
  {t:'Sua segurança é prioridade',k:'segurança trânsito chuva acidente capacete',s:'A entrega nunca vem antes da sua segurança.',b:`<p>Respeite as regras de trânsito, use capacete e equipamentos obrigatórios e adapte a condução às condições da via.</p><h2>Chuva</h2><p>Reduza a velocidade, aumente a distância e procure abrigo seguro em situação de risco. Informe a operação quando a condição impedir o deslocamento normal.</p><h2>Acidente ou pane</h2><p>Primeiro cuide da segurança. Depois avise o grupo e o suporte com localização e situação objetiva. Não tente esconder uma ocorrência.</p>`},
  {t:'Comunicação é tudo',k:'grupo suporte mensagem aviso ocorrência',s:'Use o canal certo e informe o que realmente ajuda a operação.',b:`<p>O grupo da loja existe para o período em andamento: chegada, coleta, rota, dificuldade com cliente, retorno e falhas no aplicativo.</p><h2>Assuntos gerais</h2><p>Reservas, pagamentos, documentos, sugestões e dúvidas administrativas devem ser enviados ao suporte, não ao grupo do cliente.</p><h2>Como escrever</h2><p>Informe seu nome, cliente, pedido, problema e o que já tentou. Evite mensagens vagas como “deu ruim” ou “não aparece”.</p>`},
  {t:'Organização faz a diferença',k:'organização rotina checklist documentos combustível',s:'Prepare-se antes do período para não transferir seu problema à operação.',b:`<p>Antes de sair de casa, confira combustível, pneus, freios, documentação, bateria, internet, bag, capa de chuva e endereço da reserva.</p><p>Chegar sem equipamento, sem combustível ou sem saber onde é o local compromete o cliente e os outros parceiros.</p>`},
  {t:'Equipamentos obrigatórios',k:'bag própria isopor celular moto cnh capa chuva',s:'Veja o que é responsabilidade do parceiro levar.',b:`<p>O parceiro deve possuir motocicleta em condições de uso, CNH válida, celular com internet, bag própria adequada e capa de chuva.</p><h2>Bag própria</h2><p>A bag é obrigatória e não deve ser esperada da loja. Para pizzas, utilize preferencialmente bag rígida de isopor, limpa, seca e firme.</p><h2>Empréstimos</h2><p>Se algum cliente disponibilizar equipamento excepcionalmente, poderá exigir termo de responsabilidade. Isso não cria obrigação de empréstimo futuro.</p>`},
  {t:'Atendimento de excelência',k:'cliente educação entrega porta respeito',s:'Como representar a OE com educação e objetividade.',b:`<p>Cumprimente, confirme o nome ou pedido, entregue com cuidado e mantenha postura respeitosa. Não discuta sobre atraso, valor, endereço ou qualidade do produto.</p><p>Quando houver reclamação, diga que acionará o suporte e siga a orientação recebida.</p>`},
  {t:'Foco no que importa',k:'turno distração celular conversa prioridade',s:'Durante o período, mantenha atenção na operação.',b:`<p>Evite ausências, conversas que impeçam ouvir chamadas e uso do celular que atrapalhe notificações. Durante o período confirmado, mantenha disponibilidade para as entregas.</p>`},
  {t:'Gestão de tempo e prioridades',k:'tempo rota atraso prioridade pedido',s:'Organize a rota e comunique qualquer atraso real.',b:`<p>Siga a rota indicada, observe o trânsito e evite paradas sem relação com a entrega. Quando houver bloqueio, endereço incorreto ou atraso relevante, informe o grupo antes que a loja precise procurar você.</p>`},
  {t:'Comunicação que conecta e resolve',k:'mensagem clara print localização pedido',s:'O modelo de mensagem que permite resposta rápida.',b:`<p>Uma boa mensagem contém: nome, cliente, número do pedido, localização, problema e evidência quando necessária.</p><p>Exemplo: “Sou João, operação Fratelli, pedido 158. Estou no endereço, mas o número não existe. Liguei duas vezes e enviei mensagem. Segue foto da fachada.”</p>`},
  {t:'Profissionalismo em cada detalhe',k:'postura respeito cliente loja uniforme higiene',s:'Pequenas atitudes protegem sua imagem e a operação.',b:`<p>Mantenha bag limpa, apresentação adequada, comunicação respeitosa e cuidado com o pedido. Não exponha clientes ou lojas em redes sociais e não compartilhe dados de pedidos.</p>`},
  {t:'Segurança em primeiro lugar sempre',k:'direção defensiva pressa velocidade',s:'Nenhuma meta justifica condução perigosa.',b:`<p>Não aceite pressão para ultrapassar limites de segurança. Em caso de risco, pare em local seguro, comunique a operação e aguarde orientação.</p>`},
  {t:'Cuide de você, cuide da entrega',k:'pizza bag lombada estabilidade alimento',s:'Como transportar pedidos sem danificar o produto.',b:`<p>Mantenha a bag firme e nivelada. Em lombadas e curvas, reduza a velocidade para evitar que a bag bata nas costas ou no banco.</p><p>Para pizza, evite inclinar a bag e não use bag flexível sem estrutura quando isso comprometer a estabilidade.</p>`},
  {t:'Quer reservar a semana?',k:'domingo disponibilidade dias horário suporte',s:'Passo a passo para informar disponibilidade.',b:`<h2>Quando enviar</h2><p>Todo domingo, envie ao suporte os dias e períodos em que realmente poderá comparecer.</p><h2>Como enviar</h2><p>Escreva de forma completa: “Disponibilidade: terça, quinta e sexta, das 18h às 0h.”</p><h2>Atenção</h2><p>Informar disponibilidade não significa confirmação. Aguarde a agenda oficial enviada na segunda-feira.</p>`},
  {t:'Cancelou um dia?',k:'cancelamento cobertura substituto aviso',s:'O que acontece quando você não pode cumprir uma reserva confirmada.',b:`<p>Avise assim que souber. A OE primeiro tenta uma cobertura avulsa. Se não encontrar, pode reabrir o dia cancelado junto com os demais dias reservados da semana para aumentar a chance de reposição.</p><h2>Posso indicar alguém?</h2><p>Sim, mas o substituto precisa ser aprovado pela Osasco Express antes de assumir.</p><h2>Cancelamentos frequentes</h2><p>Podem reduzir a prioridade em reservas futuras porque dificultam a estabilidade da operação.</p>`},
  {t:'Todos somos parceiros OE',k:'vaga fixa cliente ponto autonomia',s:'Entenda por que ninguém é dono de loja, vaga ou ponto.',b:`<p>Os estabelecimentos são clientes da Osasco Express e as reservas pertencem à operação. Mesmo que você trabalhe frequentemente no mesmo local, isso não cria vaga permanente.</p><p>A OE pode reorganizar parceiros conforme demanda, disponibilidade e necessidade de cada cliente.</p>`},
  {t:'Diária garantida e suas entregas',k:'diária ajuda custo 45 55 seis horas entrega',s:'Como a ajuda de custo se soma às entregas.',b:`<p>A diária garantida é uma ajuda de custo pelo período previamente aceito e cumprido. Ela não substitui o pagamento das entregas.</p><h2>Valores gerais</h2><p>Segunda a quinta: R$ 45 por período de até seis horas. Sexta, sábado, domingo e feriados: R$ 55 por período de até seis horas.</p><h2>Dois períodos</h2><p>Quem cumpre dois períodos no mesmo dia recebe duas diárias. Valores específicos de um cliente, quando informados oficialmente, prevalecem para aquela operação.</p>`},
  {t:'Pagamentos: terça-feira, das 8h às 18h',k:'pagamento pix terça horario fechamento',s:'Quando o valor é enviado e o que conferir antes.',b:`<p>Os pagamentos são realizados toda terça-feira, entre 8h e 18h, em horário comercial.</p><p>Antes desse período, confira o relatório no aplicativo. Não considere atraso enquanto o horário oficial ainda estiver em andamento.</p><p>Se após as 18h houver divergência, envie ao suporte seu nome, período e captura do relatório.</p>`},
  {t:'Atrasou? Fique ligado',k:'atraso 15 minutos desconto proporcional diária',s:'Como o atraso impacta o registro do período.',b:`<p>O horário combinado é a referência de início. Atrasos superiores a 15 minutos podem gerar desconto proporcional na diária garantida.</p><p>Atrasos repetidos também podem levar à reabertura de reservas futuras. Se houver imprevisto, avise antes do horário sempre que possível.</p>`},
  {t:'Seu pagamento na palma da mão',k:'app ganhos entregas valores pix',s:'Onde acompanhar os registros financeiros.',b:`<p>Use o aplicativo para acompanhar entregas, valores e registros financeiros disponíveis. Mantenha seus dados de pagamento atualizados e confira o relatório antes da terça-feira.</p>`},
  {t:'Seu relatório na palma da mão',k:'relatório entregas diárias conferência',s:'O que aparece no relatório e quando ele fica completo.',b:`<p>As entregas são registradas automaticamente. As diárias são lançadas conforme as operações são faturadas.</p><p>Até um dia antes do pagamento, o relatório deve estar completo para conferência. A ausência temporária de uma diária antes desse prazo não significa que ela foi perdida.</p>`},
  {t:'Algo diferente no relatório?',k:'divergência erro relatório taxa suporte print',s:'Como comunicar uma diferença sem atrasar a análise.',b:`<p>Compare dia, cliente, quantidade de entregas, taxas e diárias. Identificou diferença? Envie ao suporte uma mensagem com o item exato e captura de tela.</p><p>Exemplo: “No relatório de quinta-feira da Meridio aparecem 8 entregas, mas realizei 9. Seguem os pedidos.”</p>`},
  {t:'Reserva e confirmação',k:'segunda confirmação agenda disponibilidade',s:'Saiba diferenciar interesse, disponibilidade e reserva confirmada.',b:`<p>Disponibilidade é a informação enviada por você. Reserva confirmada é o período que a OE validou e enviou oficialmente.</p><p>Somente considere o período garantido depois da confirmação. Confira cliente, endereço, dia e horário.</p>`},
  {t:'Seu tempo vale, seu compromisso também',k:'compromisso comparecimento prioridade reserva',s:'Por que cumprir o combinado influencia novas oportunidades.',b:`<p>A OE organiza equipes contando com os períodos aceitos. Comparecimento, pontualidade e boa comunicação ajudam a manter estabilidade e aumentam a chance de novas reservas.</p><p>Isso não representa promessa de vaga fixa; é um critério operacional de confiança.</p>`},
  {t:'Acompanhe tudo no aplicativo',k:'aplicativo online notificações registro',s:'Boas práticas para não perder chamadas e registros.',b:`<p>Mantenha o aplicativo atualizado, permissões de localização e notificações ativas, internet funcionando e bateria suficiente. Ao final do período, fique offline para não continuar aparecendo no despacho automático.</p>`},
  {t:'Transparência que gera confiança',k:'transparência fechamento faturamento atualização',s:'Entenda por que alguns registros entram em momentos diferentes.',b:`<p>Entregas entram automaticamente. Diárias dependem do faturamento e conferência de cada operação. O objetivo é que o relatório esteja completo até um dia antes do pagamento.</p><p>O aplicativo continua evoluindo para tornar os lançamentos cada vez mais rápidos e transparentes.</p>`},
  {t:'Organização hoje, resultados sempre',k:'rotina histórico desempenho compromisso',s:'Como construir um histórico operacional confiável.',b:`<p>Confirme apenas o que pode cumprir, chegue preparado, comunique imprevistos e confira seus registros. A consistência reduz problemas e facilita novas oportunidades.</p>`},
  {t:'Você representa a marca OE',k:'marca conduta encerramento respeito',s:'A postura do parceiro impacta toda a rede.',b:`<p>Durante a operação, sua conduta é percebida pelo cliente final e pelo estabelecimento. Respeito, cuidado com o pedido, segurança e comunicação preservam a confiança construída pela Osasco Express.</p><h2>Ao terminar o período</h2><p>Confirme que não há entrega aberta, avise quando necessário e fique offline no aplicativo.</p>`}
];
const files = [
'01.webp',
'02.webp',
'03.webp',
'04.webp',
'05.webp',
'06.webp',
'07.webp',
'08.webp',
'09.webp',
'10.webp',
'11.webp',
'12.webp',
'13.webp',
'14.webp',
'15.webp',
'16.webp',
'17.webp',
'18.webp',
'19.webp',
'20.webp',
'21.webp',
'22.webp',
'23.webp',
'24.webp',
'25.webp',
'26.webp',
'27.webp',
'28.webp',
'29.webp',
'30.webp',
'31.webp',
'32.webp'
];
let page=Number(localStorage.getItem('oe_page')||0); const viewed=new Set(JSON.parse(localStorage.getItem('oe_viewed')||'[]')); viewed.add(page);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('oe_page',page);localStorage.setItem('oe_viewed',JSON.stringify([...viewed]));}
function renderPage(dir='next'){const stage=$('#pageStage');stage.innerHTML=`<div class="page-loading" aria-hidden="true"></div><img src="assets/gibi/${encodeURIComponent(files[page])}" alt="${ARTICLES[page].t}" decoding="async">`;const img=stage.querySelector('img');img.addEventListener('load',()=>stage.querySelector('.page-loading')?.remove(),{once:true});stage.classList.remove('turn-next','turn-prev');void stage.offsetWidth;stage.classList.add(dir==='prev'?'turn-prev':'turn-next');$('#readerCounter').textContent=`${page+1}/32`;$('#pageTitle').textContent=ARTICLES[page].t;viewed.add(page);save();renderProgress();$$('#dots button').forEach((b,i)=>b.classList.toggle('active',i===page));requestAnimationFrame(()=>$$('#dots button')[page]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'}));preloadNearby();}
function renderProgress(){const n=viewed.size,p=Math.round(n/32*100);$('#progressLabel').textContent=`${n} de 32`;$('#progressBar').style.width=p+'%';document.querySelector('.progress-track')?.setAttribute('aria-valuenow',String(n));$('#readStatus').textContent=n<32?`Telas vistas: ${n}/32`:'✓ Todas as 32 telas foram visualizadas';$('#confirmBtn').disabled=n<32;const start=$('#startReadingBtn');if(start)start.textContent=n>1&&n<32?'Continuar leitura':n===32?'Revisar livreto':'Começar leitura';}
function preloadNearby(){[1,2].forEach(step=>{[page+step,page-step].forEach(i=>{const idx=(i+32)%32;const img=new Image();img.src=`assets/gibi/${encodeURIComponent(files[idx])}`})})}function go(n,dir){page=(n+32)%32;renderPage(dir)}
$('#prevPage').onclick=()=>go(page-1,'prev');$('#nextPage').onclick=()=>go(page+1,'next');$('#mobilePrev').onclick=()=>go(page-1,'prev');$('#mobileNext').onclick=()=>go(page+1,'next');
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(page+1,'next');if(e.key==='ArrowLeft')go(page-1,'prev')});
let sx=0;$('#reader').addEventListener('touchstart',e=>sx=e.changedTouches[0].clientX,{passive:true});$('#reader').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45) dx<0?go(page+1,'next'):go(page-1,'prev')},{passive:true});
const dots=$('#dots');ARTICLES.forEach((_,i)=>{const b=document.createElement('button');b.onclick=()=>go(i,i>page?'next':'prev');dots.appendChild(b)});
function articleHTML(i){const a=ARTICLES[i];return `<article class="article-body"><span class="article-number">ARTIGO ${String(i+1).padStart(2,'0')} DE 32</span><h1>${a.t}</h1><p><strong>${a.s}</strong></p>${a.b}<h2>Precisa de ajuda?</h2><p>Para ocorrência durante o período, use o grupo da operação. Para assunto geral, fale com o suporte dos parceiros: <strong>(11) 92478-2555</strong>, de segunda a sexta, das 10h às 20h.</p></article>`}
function openArticle(i){$('#dialogContent').innerHTML=articleHTML(i);$('#articleDialog').showModal();$('#articleDialog').scrollTop=0}
$('#openArticle').onclick=()=>openArticle(page);$('#closeArticle').onclick=()=>$('#articleDialog').close();
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function search(q){q=normalize(q.trim());return ARTICLES.map((a,i)=>({...a,i})).filter(a=>!q||normalize(a.t+' '+a.k+' '+a.s+' '+a.b.replace(/<[^>]+>/g,' ')).includes(q))}
function renderCards(q=''){const r=search(q),grid=$('#articleGrid');$('#resultsInfo').textContent=q?`${r.length} resultado(s) para “${q}”`:`${r.length} assuntos disponíveis`;grid.innerHTML=r.length?r.map(a=>`<button class="article-card" data-i="${a.i}"><span class="number">${String(a.i+1).padStart(2,'0')}</span><h3>${a.t}</h3><p>${a.s}</p></button>`).join(''):`<div class="empty">Nenhum resultado. Tente outra palavra.</div>`;$$('.article-card').forEach(b=>b.onclick=()=>openArticle(Number(b.dataset.i)))}
const chips=['Reserva','Pagamento','Atraso','Taxa','Cliente','Bag','Aplicativo','Suporte'];$('#quickChips').innerHTML=chips.map(c=>`<button>${c}</button>`).join('');$$('#quickChips button').forEach(b=>b.onclick=()=>{$('#knowledgeSearch').value=b.textContent;renderCards(b.textContent)});$('#knowledgeSearch').oninput=e=>renderCards(e.target.value);$('#clearSearch').onclick=()=>{$('#knowledgeSearch').value='';renderCards()};
function openGlobal(){renderGlobal('');$('#searchDialog').showModal();setTimeout(()=>$('#globalSearch').focus(),50)}
function renderGlobal(q){const r=search(q);$('#globalResults').innerHTML=r.map(a=>`<div class="global-result" data-i="${a.i}"><strong>${a.t}</strong><small>${a.s}</small></div>`).join('');$$('.global-result').forEach(x=>x.onclick=()=>{$('#searchDialog').close();openArticle(Number(x.dataset.i))})}
$('#searchBtn').onclick=openGlobal;$('#closeSearch').onclick=()=>$('#searchDialog').close();$('#globalSearch').oninput=e=>renderGlobal(e.target.value);$('#clearGlobal').onclick=()=>{$('#globalSearch').value='';renderGlobal('')};
const drawer=$('#drawer'),scrim=$('#scrim');function toggleDrawer(on){drawer.classList.toggle('open',on);scrim.classList.toggle('show',on);drawer.setAttribute('aria-hidden',String(!on))}$('#menuBtn').onclick=()=>toggleDrawer(true);$('#closeMenu').onclick=()=>toggleDrawer(false);scrim.onclick=()=>toggleDrawer(false);$$('.drawer a').forEach(a=>a.onclick=()=>toggleDrawer(false));
$('#confirmationForm').onsubmit=async e=>{e.preventDefault();const msg=$('#formMessage');const payload={nome:$('#nome').value.trim(),sobrenome:$('#sobrenome').value.trim(),telas_vistas:viewed.size,data:new Date().toISOString(),declaracao:true};if(viewed.size<32)return;$('#confirmBtn').disabled=true;$('#confirmBtn').textContent='Enviando...';try{const endpoint=window.OE_CONFIG?.confirmationEndpoint;if(endpoint){await fetch(endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});}localStorage.setItem('oe_confirmation',JSON.stringify(payload));msg.innerHTML='<strong>✓ Leitura confirmada!</strong><br>Seu registro foi concluído.';$('#confirmBtn').textContent='Leitura confirmada';}catch(err){msg.textContent='Não foi possível enviar agora. Confira sua conexão e tente novamente.';$('#confirmBtn').disabled=false;$('#confirmBtn').textContent='Confirmar leitura';}};
renderPage();renderCards();
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});
